name       : gzip
version    : '1.11'
release    : 13
source     :
    - https://ftp.gnu.org/gnu/gzip/gzip-1.11.tar.xz : 9b9a95d68fdcb936849a4d6fada8bf8686cddf58b9b26c9c4289ed0c92a77907
homepage   : http://www.gzip.org/
license    : GPL-3.0-or-later
optimize   : speed
summary    : gzip (Compression utility)
component  : system.base
description: |
    gzip (GNU zip) is a compression utility designed to replace compress. gzip was written by Jean-loup Gailly (jloup@gzip.org) and Mark Adler.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
