name       : gzip
version    : 1.9
release    : 10
source     :
    - https://ftp.gnu.org/gnu/gzip/gzip-1.9.tar.xz : ae506144fc198bd8f81f1f4ad19ce63d5a2d65e42333255977cf1dcf1479089a
homepage   : http://www.gzip.org/
license    : GPL-3.0
optimize   : speed
summary    : gzip (Compression utility)
component  : system.base
description: |
    gzip (GNU zip) is a compression utility designed to replace compress. gzip was written by Jean-loup Gailly (jloup@gzip.org) and Mark Adler.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
