name        : gzip
version     : 1.6
release     : 3
source      :
    - http://ftp.gnu.org/gnu/gzip/gzip-1.6.tar.xz : 37dfed1a485d53212c43b3fa2a7c7952f09bf5cd86e37121c222341ee1b27847
homepage    : http://www.gzip.org
license     :
    - GPLv3+
summary     : gzip (Compression utility)
description : |
    gzip (GNU zip) is a compression utility designed to replace compress. gzip was written by Jean-loup Gailly (jloup@gzip.org) and Mark Adler.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
