name        : gzip
version     : 1.7
release     : 7
source     :
    - http://ftp.gnu.org/gnu/gzip/gzip-1.7.tar.xz : fb31c57e7ce7703596ef57329be7cc5c5fd741b4a0f659fea7ee6a54706b41ab
homepage    : http://www.gzip.org
license     :
    - GPL-3.0
optimize    : speed
summary     : gzip (Compression utility)
component   : system.base
description : |
    gzip (GNU zip) is a compression utility designed to replace compress. gzip was written by Jean-loup Gailly (jloup@gzip.org) and Mark Adler.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
